### ISSUE TITLE
Misleading error messages when validating JSON data

### ISSUE THREAD

**Issue by whimboo** [anweiss/cddl#140]
Invalid JSON data that eg. contains a wrong type for the value within a subtype of the CDDL definition the error message as printed is misleading. If doable it should be bound to the nearest possible CDDL type definition.

Take the following example:
```CDDL
Command = (
  CommandFoo //
  CommandBar
)

CommandFoo = {
  method: "foo-command",
  params: text
}

CommandBar = {
  method: "bar-command",
  params: bool
}
```

```JSON
{
  "method": "bar-command",
  "params": 2
}
```

The failure as shown is the following:
```
[ERROR] Validation of "data.json" failed: error validating at JSON location /method: expected value "foo-command" got "bar-command"
error validating at JSON location /params: expected type text, got 2
```

By reading the error output it's not clear that `bar-command` was actually send and that it's `params` value was wrong. Would it be doable to output something like the following instead?

```
[ERROR] Validation of "data.json" failed: error validating at JSON location /method: "bar-command", /params: expected type text, got 2
```

**Comment by anweiss** [comment]
@whimboo this is actually working as expected. Per https://www.rfc-editor.org/rfc/rfc8610#section-2.2.4, the first type rule is used as the root type for validating a document. In this case, the root type is `CommandFoo` and not the `Command` group. So the `{ "method": "bar-command", "params": 2 }` JSON is invalid because it's expecting the `method` entry to be of value `"foo-command"` and the `params` entry to be of type `text`l.

**Comment by anweiss** [comment]
To your point, though, this can definitely be made more clear by identifying the root type used for validating the document in the error message.

**Comment by whimboo** [comment]
I see, but adding a specific new root doesn't change that:

```
Message = {
  Command
}

Command = (
  CommandFoo //
  CommandBar
)

CommandFoo = {
  method: "foo-command",
  params: text
}

CommandBar = {
  method: "bar-command",
  params: bool
}
```

Given that I don't know how selection of the right group entry should happen (might have to read the RFC in detail) I wonder if specific entries could be considered with a higher priority eg, the one that is listed at the top, or those that have a fixed value set. With the latter option `CommandBar` would only be chosen given that the value of the `method` field is exactly the same and doesn't apply to any other commands in the `Command` group listing.

**Comment by anweiss** [comment]
Even so, in this example, validation will still fail because it's going to attempt to validate both the `CommandFoo` and `CommandBar` group choices, neither of which match the `{ "method": "bar-command", "params": 2 }` JSON. Per https://www.rfc-editor.org/rfc/rfc8610#section-2.2.2, `//` binds more weakly than other CDDL operators, thus the validation is implemented such that all group choices will be checked until validation of the entire choice is successful. Even if parts of the group choice validate successfully this is still considered invalid for that particular group choice. The only way to allow for validation to be successful when parts of the group choice are valid is to use occurrence operators such as `?` or `*`.

**Comment by anweiss** [comment]
Hey @whimboo ... https://github.com/anweiss/cddl/pull/143 was merged which identifies the root type used during validation. Going to close this. Feel free to re-open if you still have some concerns. Thanks
